### ISSUE TITLE
当前版本问题太多！不建议BT用户使用，另外现有版本无法通过配置参数临时关闭debugbar

### ISSUE THREAD

**Issue by 9007967** [top-think/think-debugbar#6]
1、BT 面板 静态资源 css和js不走 php解析 安装会出现大量静态文件 404错误 请谨慎安装。
2、此扩展当前版本 未提供关闭参数，安装后暴露出所有配置参数，线上项目为了安全 禁止安装。

**Comment by yunwuxin** [comment]
1、nginx的配置不对，应先检查文件是否存在
2、建议放在require-dev里

**Comment by 9007967** [comment]
> 1、nginx的配置不对，应先检查文件是否存在
> 2、建议放在require-dev里

BT nginx 默认配置 我只是把遇到问题 说出来 没必要这么大反应

**Comment by yunwuxin** [comment]
？
我只是回复的你疑问

**Comment by 9007967** [comment]
删了 不用了 拜拜吧您嘞
